site_name: IHC Grupo 7 - Sabin
theme:
  name: material
  favicon: assets/logo-sabin.png
  logo: assets/logo-sabin.png
  icon:
    logo: /assets/logo-sabin.png
  language: pt-BR
  font:
    text: Inter
    code: JetBrains Mono
  palette:
    - scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/weather-night
        name: Modo escuro
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Modo claro
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - content.code.copy
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.follow
    - search.suggest
    - search.share
    - content.code.annotate
    - header.autohide
nav:
  - Home: index.md
  - Planejamento:
      - Cronograma: 
          - Heatmap: planejamento/heatmap.md
          - Planejado: planejamento/cronograma.md
          - Executado: planejamento/cronogramaexec.md
      - Processo de Design: planejamento/processoDesign.md
      - Sites avaliados: planejamento/listasites.md
  - Requisitos: 
      - Perfil de usuário: requisitos/perfilDeUsuario.md
      - Metodologia: requisitos/metodologiaParaPerfil.md
      - Personas: requisitos/persona.md
      - Cenário: requisitos/cenario.md
  - Ferramentas: Ferramentas.md
  - Atas de reunião: 
          - Reunião 1: atasDeReuniao/reuniao1.md
          - Reunião 2: atasDeReuniao/reuniao2.md
          - Reunião 3: atasDeReuniao/reuniao3.md
  - Verificações: verificacoes.md

plugins:
  - search:
      lang: pt

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - toc:
      permalink: true
      title: Nesta página
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/
  generator: false
  status:
    new: Novo
    deprecated: Obsoleto
extra_css:
  - assets/extra.css
